# FUNDING.yml
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# 如果你想支持这个项目，可以通过以下方式赞助
# 取消注释并填写你的信息

# github: [worldop123]
# patreon: # 替换为你的 Patreon 用户名
# open_collective: # 替换为你的 Open Collective 用户名
# ko_fi: # 替换为你的 Ko-fi 用户名
# tidelift: # npm/aether-os
# community_bridge: # 替换为你的 Community Bridge 用户名
# liberapay: # 替换为你的 Liberapay 用户名
# issuehunt: # 替换为你的 IssueHunt 用户名
# otechie: # 替换为你的 Otechie 用户名
# lfx_crowdfunding: # 替换为你的 LFX Crowdfunding 项目名
# custom: # 自定义赞助链接
